sudo: required
language: c
env:
  - MAKEFLAGS="-j2"
matrix:
  include:
    - env: ARCH_TRAVIS_ARCH="i686"
    - env: ARCH_TRAVIS_ARCH="x86_64"
arch:
  repos:
    - archlinuxcn=http://repo.archlinuxcn.org/$arch
    - haskell-core=http://xsounds.org/~haskell/core/$arch
  packages:
    - haveged
    - archlinux-keyring
    - archlinuxcn-keyring
  script:
    - uname -a
    - sudo /usr/bin/haveged -F -w 1024 -v 1 &
    - sudo pacman-key --init
    - sudo pacman-key -r 4209170B
    - sudo pacman-key --lsign-key 4209170B
    - sudo pacman-key --populate archlinux
    - sudo pacman-key --populate archlinuxcn
    - git clone git://github.com/archlinuxcn/repo
    - cd repo/julia-git && makepkg -s  --noconfirm

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
