sudo: required
language: c
matrix:
  include:
    - env: BUILD_ARCH="i686"
    - env: BUILD_ARCH="x86_64"
arch:
  repos:
    - archlinuxcn=http://repo.archlinuxcn.org/$arch
    - haskell-core=http://xsounds.org/~haskell/core/$arch
  packages:
    - devtools-cn-git
    - haveged
  script:
    - sudo systemctl start haveged
    - sudo pacman-key --init
    - git clone git://github.com/archlinuxcn/repo
    - cd repo/julia-git;
      sudo archlinuxcn-$BUILD_ARCH-build

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
