name = "SortingAlgorithms"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
authors = ["JuliaStats"]
version = "0.3.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1"
